apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: lptvlru1z-python
  janus-idp.io/tekton: lptvlru1z-python
  backstage.io/kubernetes-id: lptvlru1z-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: lptvlru1z-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
